repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: mixed-line-ending
    args:
    - "--fix=lf"

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    args: [--whitespaces-count, '2']  # defaults to: 4

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args:
    - "--write-changes"
    - "--ignore-words=.codespellignore"
    additional_dependencies:
      - tomli
    exclude: '^pdm\.lock$'
